#' @title Calculate replicate weights and summary statistics
#' @description Takes the output of `cluster_gen` to calculate the replicate weights as well as some summary statistics
#' @param data list of background questionnaire data (typically generated by `cluster_gen`)
#' @param method replication method. Can be "jackknife", "BRR" or "BRR Fay"
#' @param k deflating weight factor (used only when `method = "BRR Fay")
#' @param print_stats if `TRUE`, includes some statistics concerning the background questionnaire questions
#' @details Replicate weights can be calculated using the Jackknife for unstratified two-stage sample designs or Balanced Repeated Replication (BRR) with or without Fay's modification.
#' According to OECD (2015), PISA uses the Fay method with a factor of 0.5. This is why `k = .5` by default.
#' @seealso cluster_gen jackknife, jackknife_var
#' @references
#' OECD (2015). Pisa Data Analysis Manual.
#' Rust, K. F., & Rao, J. N. K. (1996). Variance estimation for complex surveys using replication techniques. Statistical methods in medical research, 5(3), 283-310.
#' @return list with data and, if requeted, some statistics
#' @export
calc_replicate_weights <- function(data, method, k = .5, print_stats = FALSE)
{
    # Verification =============================================================
    if (k < 0 | k > 1) stop ("k must be between 0 and 1")
    
    # Basic variable creation ==================================================
    num_lvl <- length(data)
    new_bg <- list()
    replicate_stats <- list()

    # Analysing each dataset separately ========================================
    for (lvl in seq(num_lvl)) {
        lvl_name <- names(data)[lvl]
        num_sublvl <- length(data[[lvl]])

        for (sublvl in seq(num_sublvl)) {
            bg <- data[[lvl_name]][[sublvl]]
            w_cols <- names(bg)[grep("weight", names(bg))]

            # Remove uninsteresting columns ------------------------------------
            data_cols <- grep("subject|ID|weight", names(bg), invert = TRUE)
            data_cols <- names(bg)[data_cols]

            # Calculating replicate weights ------------------------------------
            if (method == "Jackknife") {
                replicates <- jackknife(bg)
                rep_stats <- replicate_var(data_whole = bg,
                                            data_rep   = replicates,
                                           method     = "Jackknife",
                                            theta      = data_cols,     
                                            full_output = TRUE)
                if (length(w_cols) > 0) {
                    G <- nrow(bg)
                    bg <- recalc_final_weights(bg, w_cols, G / (G - 1))
                }
            } else if (method == "BRR") {
                # DONE: Add BRR
                replicates <- brr(bg)
                if (length(w_cols) > 0) {
                    # TODO: redo? Apply 0 weights instead of dropping from data?
                    bg <- recalc_final_weights(bg, w_cols, 2)
                }
                # DONE: add brr_var (joined with jack_var)
                rep_stats <- replicate_var(data_whole = bg,
                                           data_rep   = replicates,
                                           method     = "BRR",
                                           theta      = data_cols,     
                                           full_output = TRUE)
                # TODO: Add Fay's weights
                stop("BRR Fay not yet implemented.")
            } else {
                stop("Invalid method for calculating replicate weights.")
            }

            # Organizing statistics --------------------------------------------
            if (print_stats) {
                means <- rep_stats$theta_whole
                vars  <- rep_stats$sigma2
                stats <- rbind(means, sqrt(vars))
                rownames(stats) <- c("mean", "sd")
            }

            # Putting data and stats into common list for output ---------------
            bg -> new_bg[[lvl_name]][[sublvl]]
            if (print_stats) stats -> replicate_stats[[lvl_name]][[sublvl]]
        }
    }

    # Assembling output ========================================================
    out <- new_bg
    if (print_stats) out <- list(data = out, statistics = replicate_stats)
    return(out)
}