#' @title Calculate replicate weights and summary statistics
#' @description Takes the output of `cluster_gen` to calculate the replicate weights as well as some summary statistics
#' @param data list of background questionnaire data (typically generated by `cluster_gen`)
#' @param var_method if other than `none`, calculates replicate weights. Can be "jackknife", "BRR" or "BRR Fay"
#' @param print_stats if `TRUE`, includes some statistics concerning the background questionnaire questions
#' @param verbose if `TRUE`, prints summary
#' @details Replicate weights can be calculated using the Jackknife for unstratified two-stage sample designs or Balanced Repeated Replication (BRR) with or without Fay's modification.
#' @seealso cluster_gen jackknife, jackknife_var
#' @references
#'     OECD (2015). Pisa Data Analysis Manual.
#'     Rust, K. F., & Rao, J. N. K. (1996). Variance estimation for complex surveys using replication techniques. Statistical methods in medical research, 5(3), 283-310.
#' @return list with data and, if requeted, some statistics
#' @export
calc_replicate_weights <- function(data, var_method = "none",
                                   print_stats = TRUE, verbose = FALSE)
{
    # Basic variable creation ==================================================
    num_lvl <- length(data)
    new_bg <- list()
    replicate_stats <- list()

    # Analysing each dataset separately ========================================
    for (lvl in seq(num_lvl)) {
        lvl_name <- names(data)[lvl]
        num_sublvl <- length(data[[lvl]])

        for (sublvl in seq(num_sublvl)) {
            #sublvl_name <- names(data[[lvl]])[sublvl]
            bg <- data[[lvl_name]][[sublvl]]

            # Remove uninsteresting columns
            data_cols <- grep("subject|ID|weight", names(bg), invert = TRUE)
            data_cols <- names(bg)[data_cols]

            if (verbose) {
                message("\nSummary statistics for ", lvl_name, "[[", sublvl, "]]")
                print(summary(bg[data_cols]))
            }

            # Calculating replicate weights ------------------------------------
            if (var_method == "Jackknife") {
                replicates <- jackknife(bg)
                jack_stats <- jackknife_var(data_whole = bg,
                                            data_rep   = replicates,
                                            theta      = data_cols,     
                                            full_output = TRUE)
                
                w_cols <- grep("weight", names(bg))
                if (length(w_cols) > 0) {
                    G <- nrow(bg)
                    bg$replicate.weight <- G / (G - 1)
                    new_w_cols <- grep("weight", names(bg))
                    w_cols_final <- w_cols[length(w_cols)]
                    w_cols_inter <- new_w_cols[new_w_cols != w_cols_final]
                    bg[w_cols_final] <- apply(bg[w_cols_inter], 1, prod)
                }
                means <- jack_stats$theta_whole
                vars  <- jack_stats$sigma2_jack
                stats <- rbind(means, sqrt(vars))
                rownames(stats) <- c("mean", "sd")
            }
            # TODO: Add BRR
            # TODO: Add Fay's weights
            bg -> new_bg[[lvl_name]][[sublvl]]
            stats -> replicate_stats[[lvl_name]][[sublvl]]
        }
    }

    # Assembling output ========================================================
    out <- new_bg
    if (print_stats) out <- list(data = out, statistics = replicate_stats)
    return(out)
}